# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|  
  # Configuramos un nombre a nuestra máquina para que tenga un friendly name en VirtualBox
  config.vm.provider "virtualbox" do |v|
    v.name = "MariaDB"
  end
  # ubuntu es el Box base que hemos elegido
  config.vm.box = "ubuntu/focal64"
  # Port forwarding del host al guest
  config.vm.network "forwarded_port", guest: 3306, host: 3306
  # Vamos a montar todos los archivos que se encuentren en el directorio a la carpeta /vagrant del guest
  config.vm.synced_folder "data", "/home/vagrant/shared_folder"
  # Este es el shell de aprovisionamiento que se ejecutará
  config.vm.provision "shell", path: "pasos.sh"  
end
