apiVersion: apps/v1
kind: Deployment
metadata:
  name: cliente-deployment
  labels:
    app: cliente
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cliente
  template:
    metadata:
      labels:
        app: cliente
    spec:
      containers:
        - name: cliente
          image: ahernandez141/cliente_proyecto_kubernetes
          env:
            - name: DB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: api-db-secrets
                  key: DB_ROOT_PASSWORD
            - name: KEY
              valueFrom:
                secretKeyRef:
                  name: api-db-secrets
                  key: KEY
            - name: MYSQL_SERVICE_HOST
              value: mariadb-service
