apiVersion: batch/v1
kind: Job
metadata:
  name: cliente-job
  labels:
    app: cliente
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: cliente
          image: ahernandez141/cliente_proyecto_kubernetes
          env:
            - name: DB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: api-db-secrets
                  key: DB_ROOT_PASSWORD
            - name: KEY
              valueFrom:
                secretKeyRef:
                  name: api-db-secrets
                  key: KEY
            - name: MYSQL_SERVICE_HOST
              value: mariadb-service
          
